FROM python:3.12.4-alpine3.20
RUN pip install --no-cache-dir fastapi uvicorn websockets asyncio aiohttp aiofiles aiopath python-multipart stringcase
RUN mkdir -p /opt/server
WORKDIR /opt/server
ENTRYPOINT ["python", "-u", "server.py"]